import React from 'react';
import { Scale, Shield, FileText, Mail, Building, Server } from 'lucide-react';
import PageWrapper from '@/components/PageWrapper';
import { useLanguage } from '@/components/LanguageContext';

export default function Legal() {
  const { t, language } = useLanguage();

  const sections = [
    { icon: Building, title: t('editor'), content: t('editorDesc') },
    { icon: Server, title: t('hosting'), content: t('hostingDesc') },
    { icon: FileText, title: t('intellectualProperty'), content: t('ipDesc') },
    { icon: Shield, title: t('dataProtection'), content: t('dataDesc') },
    { icon: Scale, title: t('termsOfUse'), content: language === 'fr' 
      ? "L'utilisation de iGPT implique l'acceptation des présentes conditions. Les visuels générés doivent respecter les lois en vigueur."
      : "Using iGPT implies acceptance of these terms. Generated visuals must comply with applicable laws." 
    },
    { icon: FileText, title: t('refundPolicy'), content: language === 'fr'
      ? "Les crédits achetés ne sont pas remboursables. Les abonnements peuvent être annulés à tout moment."
      : "Purchased credits are non-refundable. Subscriptions can be cancelled at any time."
    },
    { icon: Shield, title: t('liability'), content: language === 'fr'
      ? "iGPT ne peut être tenu responsable de l'utilisation des visuels générés par les utilisateurs."
      : "iGPT cannot be held responsible for the use of visuals generated by users."
    },
    { icon: Mail, title: t('contact'), content: "contact@igpt.ai" }
  ];

  return (
    <PageWrapper>
      {() => (
        <div className="space-y-6">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-white mb-2">{t('legalTitle')}</h1>
            <p className="text-white/60">{t('lastUpdate')}: {language === 'fr' ? '29 novembre 2025' : 'November 29, 2025'}</p>
          </div>

          <div className="grid gap-4">
            {sections.map((section, idx) => (
              <div key={idx} className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6">
                <div className="flex items-start gap-4">
                  <div className="p-2 rounded-lg bg-violet-600/20">
                    <section.icon className="h-5 w-5 text-violet-400" />
                  </div>
                  <div>
                    <h2 className="text-lg font-semibold text-white mb-2">{section.title}</h2>
                    <p className="text-white/60 whitespace-pre-line">{section.content}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </PageWrapper>
  );
}